name: Build
on:
  workflow_call:
    inputs:
        project-type:
            description: frontend | backend
            required: true
            type: string
        node-version:
            description: Node.js version to setup
            required: false
            type: string
        dotnet-version:
            description: DotNet version to setup
            type: string
            required: false
        azure_functionapp_package_path:
            description: Path to a deployment package
            type: string
            required: true
        cache-dependency-path:
            description: Path to cache dependencies (like node_modules, ~/.m2/repository, etc.)
            required: false
            type: string
        build-directory:
            description: Path to run the build command from
            required: false
            type: string

    secrets:
       personal_access_token:
        required: true

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
        - name: Code setup and caching dependencies
          uses: GowthamRayadurgam/ghactions-reusible/.github/actions/initial-setup@main
          with:
            project-type: ${{ inputs.project-type }}
            node-version: ${{ inputs.node-version }}
            dotnet-version: ${{ inputs.dotnet-version }}
            cache-dependency-path: ${{ inputs.cache-dependency-path }}
            azure_functionapp_package_path: ${{ inputs.azure_functionapp_package_path }}

        - if: ${{ inputs.project-type == 'backend'}}
          name: 'build the app'
          shell: bash
          run: |
            pushd './${{ inputs.azure_functionapp_package_path }}'
            dotnet publish --configuration Release --output ./output
            cd output
            zip -r ../${{ inputs.project-type }}.zip *
            popd
        
        - name: Upload build artifacts
          uses: actions/upload-artifact@v4
          with:
            name: build-artifacts-${{ inputs.project-type}}
            path: ./${{ inputs.azure_functionapp_package_path }}/${{ inputs.project-type }}.zip

        # - name: artifact upload
        #   uses: actions/upload-artifact@v4
        #   with:
        #    name: build-artifacts-${{ inputs.project-type}}
        #    path: |
        #      ${{ inputs.build-directory }}