name: Caching with npm
on:
  workflow_call:
    inputs:
        project-type:
            description: frontend | backend
            required: true
            type: string
        node-version:
            description: Node.js version to setup
            required: false
            type: string
        dotnet-version:
            description: DotNet version to setup
            type: string
            required: false
        cache-dependency-path:
            description: Path to cache dependencies (like node_modules, ~/.m2/repository, etc.)
            required: false
            type: string

        azure_functionapp_package_path:
            description: Path to a deployment package
            type: string
            required: true

    secrets:
       personal_access_token:
        required: true

jobs:
  pilot-checks:
    runs-on: ubuntu-latest
    steps:
        - name: Code setup and caching dependencies
          uses: GowthamRayadurgam/ghactions-reusible/.github/actions/initial-setup@main
          with:
            project-type: ${{ inputs.project-type }}
            node-version: ${{ inputs.node-version }}
            dotnet-version: ${{ inputs.dotnet-version }}
            cache-dependency-path: ${{ inputs.cache-dependency-path }}
            azure_functionapp_package_path: ${{ inputs.azure_functionapp_package_path }}           

        - if: ${{ inputs.project-type == 'frontend'}}
          name: Linting and testing the code
          run: |
           npm run lint
           npm run typecheck
           npm test -- --ci
           npm audit --audit-level=high